// client/vue/src/libs/feature-shell/unauthenticated-app/pages/login.vue
<script setup lang="ts">
import { useMediaQuery } from "@vueuse/core";
import { hotelRoom, logoIcon, styles } from "@firebnb/public";
import { twMerge } from "tailwind-merge";
import { useRouter } from "vue-router";
import { useLogin } from "../../../feature-data-access-api/auth";
import InputControl from "../components/input-control.vue";
import { useForm } from "vee-validate";
import Button from "../components/button.vue";
import { ref } from "vue";
import { loginUserSchema } from "../../../utils/schemas";
import { toTypedSchema } from "@vee-validate/zod";

interface LoginForm {
  email: string;
  password: string;
}

const { handleSubmit } = useForm<LoginForm>({
  validationSchema: toTypedSchema(loginUserSchema),
});

const { mutate } = useLogin();
const isLoading = ref(false);

const handleFormSubmit = handleSubmit((values) => {
  mutate(values);
});
const router = useRouter();

const isMobile = useMediaQuery("(max-width: 1024px)");

const handleNavigateToRegister = () => {
  router.push("/register");
};
</script>

<template>
  <div class="w-full flex">
    <div class="w-full flex flex-col space-y-3 px-20 py-10">
      <div class="pb-3">
        <img :src="logoIcon" />
      </div>
      <div :class="styles.paragraph">Sign in to your account</div>
      <div :class="twMerge('text-stone-400', styles.paragraph)">
        Not a member?
        <button
          className="text-primary hover:opacity-80"
          @click="handleNavigateToRegister"
        >
          Create a new account!
        </button>
      </div>
      <form @submit="handleFormSubmit" class="space-y-2.5">
        <InputControl
          label="Email address"
          type="text"
          name="email"
          placeholder="mail@example.com"
        />
        <InputControl
          label="Password"
          name="password"
          type="password"
          placeholder="********"
        />
        <Button :isLoading="isLoading" class="w-full"> Sign in </Button>
      </form>
    </div>
    <img
      v-if="!isMobile"
      :src="hotelRoom"
      class="w-full max-w-[60%] h-[100vh] object-cover object-center"
    />
  </div>
</template>

// client/react/src/libs/feature-shell/unauthenticated-app/pages/login.tsx
import { hotelRoom, logoIcon, styles } from "@firebnb/public";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { useNavigate } from "react-router-dom";
import { twMerge } from "tailwind-merge";
import { useMediaQuery } from "usehooks-ts";
import { useLogin } from "../../../feature-data-access-api/auth";
import { loginUserSchema } from "../../../utils/schemas";
import { Button } from "../components/button";
import { InputControl } from "../components/input-control";

interface LoginForm {
  email: string;
  password: string;
}

export const Login = () => {
  const { control, handleSubmit } = useForm<LoginForm>({
    resolver: zodResolver(loginUserSchema),
  });
  const { mutate } = useLogin();
  const handleFormSubmit = handleSubmit((values) => mutate(values));
  const navigate = useNavigate();
  const isMobile = useMediaQuery("(max-width: 1024px)");

  const handleNavigateToRegister = () => {
    navigate("/register");
  };

  return (
    <div className="w-full flex">
      <div className="w-full flex flex-col space-y-3 px-20 py-10">
        <div className="pb-3">
          <img src={logoIcon} />
        </div>
        <div className={styles.heading}>Sign in to your account</div>
        <div className={twMerge("text-stone-400", styles.paragraph)}>
          Not a member?{" "}
          <button
            className="text-primary hover:opacity-80"
            onClick={handleNavigateToRegister}
          >
            Create a new account!
          </button>
        </div>
        <form onSubmit={handleFormSubmit}>
          <InputControl
            label="Email address"
            control={control}
            name="email"
            placeholder="mail@example.com"
          />
          <InputControl
            label="Password"
            control={control}
            name="password"
            type="password"
            placeholder="********"
          />
          <Button className="w-full">Sign in</Button>
        </form>
      </div>
      {!isMobile && (
        <img
          src={hotelRoom}
          className="w-full h-[100vh] object-cover object-center"
        />
      )}
    </div>
  );
};
