// client/vue/src/App.vue
<template>
  <UnauthenticatedApp v-if="!data && !isLoading" />
  <AuthenticatedApp v-else-if="data && !isLoading" />
</template>

<script setup lang="ts">
import { useUser } from "./libs/feature-data-access-api/auth";
import AuthenticatedApp from "./libs/feature-shell/authenticated-app/authenticated-app.vue";
import UnauthenticatedApp from "./libs/feature-shell/unauthenticated-app/unauthenticated-app.vue";

const { data, isLoading } = useUser();
</script>

// client/react/src/App.tsx
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useUser } from "./libs/feature-data-access-api/auth";
import { AuthenticatedApp } from "./libs/feature-shell/authenticated-app/AuthenticatedApp";
import { UnauthenticatedApp } from "./libs/feature-shell/unauthenticated-app/UnauthenticatedApp";

const FireBnbApps = () => {
  const { data } = useUser();

  if (!data) {
    return <UnauthenticatedApp />;
  }

  return <AuthenticatedApp />;
};

export const App = () => {
  const queryClient = new QueryClient();

  return (
    <QueryClientProvider client={queryClient}>
      <FireBnbApps />
    </QueryClientProvider>
  );
};
